### ISSUE TITLE
Tonal example?

### ISSUE THREAD

**Issue by jneen** [PieterPenninckx/rsynth#127]
Hi! I'm just wrapping my head around writing my first plug-in. I wonder if it would be possible to provide an example that wasn't *just* noise - perhaps a sine wave synthesizer?

**Comment by PieterPenninckx** [comment]
Hi @jneen , you are having luck: I've just created a new example for the "upcoming" 0.2.0 release: [it's in the v0.2.0 branch](https://github.com/PieterPenninckx/rsynth/blob/v0.2.0/examples/). It's a sine wave synthesizer.

On the other hand, [there will be breaking changes in version 0.2.0](https://github.com/PieterPenninckx/rsynth/issues/104), so maybe it's not 100% the right time, but that's how it goes, I guess.

**Comment by PieterPenninckx** [comment]
I'm closing this issue since `rsynth` has been deprecated. See the README.md for more information.
